### PR TITLE
improvement: add `Atoms.clone()` and `remove sites by indices`, including in-place. Use `develop` branch for the PR.

### PR DESCRIPTION
**Pull request by timurbazhirov**

### CODE REVIEW

**Comment by timurbazhirov** [comment]
@knc6 The action is awaiting approval to run, it seems:

Screenshot 2024-03-20 at 12 07 30 PM

**Comment by knc6** [comment]
Could you try the following:
pip install black
black -l 79 jarvis/core/atoms.py (and any other files you modified)
add, commit,push

**Comment by timurbazhirov** [comment]
OK, should be done now. We can also consider a pre-commit hook to lint before each commit similar to https://github.com/Exabyte-io/express/blob/dev/.pre-commit-config.yaml.

**Comment by knc6** [comment]
I found a couple of issues with the PR, which should be resolved by now: 1) for numpy array, simple `assert` doesnt work e.g. `np.testing.assert_array_equal(Si2.coords, Si.coords)` is needed, 2) for `remove_sies_by_indices` there was a `not` statement missing in the if statement.

**Pull request merged**
