### PR TITLE
[WIP] Make Nix work again

### PR DESCRIPTION
**Pull request by wd15**
Use Nix on Travis CI again.

This is a work in progress, don't merge.

Also consider "squash and merge" for this pull request when it is finally merged.

### CODE REVIEW

**Comment by wd15** [comment]
@knc6 it turns out that Pandas is the problem using Nix on Travis CI. Currenlty, it either produces too much output or takes too long, but it never completes a build. I'm trying with the latest Nixpkgs commit to see if it helps. Unfortunately, we do need a Pandas even if omitted from Jarvis build as Pymatgen requires it. Also, I think it's better to only have requirements required at build time in the Jarvis setup.py. The requirements.txt can have the run time requirements as well.

**Comment by wd15** [comment]
@knc6 now have a version of Nixpkgs that builds pandas, but now have to make sure the rest of the Jarvis dependencies build for this version of Nixpkgs.

**Comment by knc6** [comment]
@wd15  I see that you have commented out the py.test part. Could you please uncomment to see how it goes?

**Comment by wd15** [comment]
@knc6 I think this is ready to merge now. It ran in less than 3 minutes once the build had been cached. Let's see how it fares once merged to master as it then needs to rebuild the cache for master, I think. Once we have the master cache I think that future pull requests and branches will use that, see https://docs.travis-ci.com/user/caching/#fetching-and-storing-caches. Remember to use squash when merging this.

**Comment by knc6** [comment]
Perfect, will merge now.

**Pull request merged**
