### PR TITLE
Implement simple linear elastic finite element solver

### PR DESCRIPTION
**Pull request by wd15**

### CODE REVIEW

**Comment by wd15** [comment]
@knc6, this is ready for your review. Tests are hanging intermittently, but those are completely independent from this pull request.

**Comment by knc6** [comment]
@wd15 The circleci filed with this pull request. Could you please take a look?

**Comment by wd15** [comment]
@knc6, Circle CI should be enabled for pull requests as well.

**Comment by wd15** [comment]
What's the link for the Circle CI build?

**Comment by knc6** [comment]
@wd15 Here is the link: https://circleci.com/gh/usnistgov/jarvis/108?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by wd15** [comment]
Try removing the `--cov=./` from the pytest in Circle CI. I'm not sure why pytest is trying to import jarvis/jarvis/dev_notes/conf.py for example. It might not be reading the setup.cfg which restricts the directories that pytest looks at because of the `--cov=./`. I can't really fix it as I don't have a way to run Circle CI without commiting to master. Can you enable Circle CI for pull requests the way Travis CI ran in this pull request?

**Pull request merged**
