### PR TITLE
Update outputs.py

### PR DESCRIPTION
**Pull request by tavazza**
I added the calculation of the Raman intensities inside parse_raman_dat

### CODE REVIEW

**Comment by knc6** [comment]
Hi @tavazza 
There are several checks that are failing:
https://github.com/usnistgov/jarvis/pull/176/checks?check_run_id=2679484832

Please install these packages first:
" pip install black pycodestyle pydocstyle"

Then 
"black -l 79 outputs.py" (The second character is small letter L)
see if these gives error:
"pycodestyle --ignore E203,W503 outputs.py"
"flake8 --ignore E203,W503 outputs.py"
" pydocstyle outputs.py"
Once you cleared those issues, please update the code on github.

**Comment by tavazza** [comment]
All checks passed.

Am I supposed to close the pull request?

**Comment by knc6** [comment]
Hi @tavazza 

No, don't close the pull request. I'll merge it and then I'll close it.

**Comment by knc6** [comment]
Everything looks good, merging it now.
Thanks again for the contribution.

**Pull request merged**
